esphome:
  name: esp32-s3-wake-word
  #friendly_name: ESP32-S3-Wake-word
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_AUDIO_BOARD_CUSTOM: "y"

psram:
  mode: quad
  speed: 80MHz

# Abilita il logging
logger:
  hardware_uart: UART0

# Abilita l'API di Home Assistant
api:
  on_client_connected:
    then:
      - delay: 50ms
      - light.turn_off: led_ww
      - micro_wake_word.start:
  on_client_disconnected:
    then:
      - voice_assistant.stop:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Esp32-S3-Wake-Word"

captive_portal:

# Script di timeout per interrompere voice_assistant se rimane in ascolto oltre 30 secondi
script:
  - id: va_timeout
    mode: restart
    then:
      - delay: 30s
      - if:
          condition:
            lambda: |-
              return id(va).is_running();
          then:
            - logger.log: "Timeout 30s: forzo stop voice_assistant e riavvio wake word"
            - voice_assistant.stop:
                id: va
            - light.turn_off: led_ww
            - delay: 50ms
            - micro_wake_word.start:

button:
  - platform: restart
    name: "Restart"
    id: but_rest

switch:
  - platform: template
    id: mute
    name: mute
    optimistic: true
    on_turn_on:
      - micro_wake_word.stop:
      - voice_assistant.stop:
      - light.turn_on:
          id: led_ww
          red: 100%
          green: 0%
          blue: 0%
          brightness: 60%
          effect: fast pulse
      - delay: 2s
      - light.turn_off:
          id: led_ww
      - light.turn_on:
          id: led_ww
          red: 100%
          green: 0%
          blue: 0%
          brightness: 30%
    on_turn_off:
      - micro_wake_word.start:
      - light.turn_on:
          id: led_ww
          red: 0%
          green: 100%
          blue: 0%
          brightness: 60%
          effect: fast pulse
      - delay: 2s
      - light.turn_off:
          id: led_ww

light:
  - platform: esp32_rmt_led_strip
    id: led_ww
    rgb_order: RGB
    pin: GPIO21  # Pin per il LED integrato
    num_leds: 1
    #rmt_channel: 0
    chipset: ws2812
    name: "on board light"
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%

# Configurazione Audio e Assistente Vocale
i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO3  # WS
    i2s_bclk_pin: GPIO2   # SCK
  - id: i2s_speaker
    i2s_lrclk_pin: GPIO6  # LRC
    i2s_bclk_pin: GPIO7   # BCLK

microphone:
  - platform: i2s_audio
    id: va_mic
    adc_type: external
    i2s_din_pin: GPIO4    # SD pin sul INMP441
    channel: left
    pdm: false
    i2s_audio_id: i2s_in
    bits_per_sample: 32bit
    #gain: 10.0

speaker:
  platform: i2s_audio
  id: va_speaker
  i2s_audio_id: i2s_speaker
  dac_type: external
  i2s_dout_pin: GPIO8     # DIN Pin del MAX98357A
  channel: mono

micro_wake_word:
  on_wake_word_detected:
    - voice_assistant.start:
        id: va
        wake_word: !lambda return wake_word;
    - light.turn_on:
        id: led_ww
        red: 30%
        green: 30%
        blue: 70%
        brightness: 60%
        effect: fast pulse
    - script.execute:
        id: va_timeout
  models:
    - model: "/root/config/wakewords/hey_trowyayoh.json"
      #probability_cutoff: 0.55
      #sliding_window_size: 5

voice_assistant:
  id: va
  microphone: va_mic
  speaker: va_speaker
  on_stt_end:
    then:
      - light.turn_off: led_ww
      - script.stop:
          id: va_timeout
  on_error:
    - script.stop:
        id: va_timeout
    - micro_wake_word.start:
  on_end:
    then:
      - light.turn_off: led_ww
      - script.stop:
          id: va_timeout
      - wait_until:
          not:
            voice_assistant.is_running:
      - micro_wake_word.start:

media_player:
  - platform: speaker
    id: troiaio
    name: Troiaio
    announcement_pipeline:
      speaker: va_speaker
