# Example: Basic go2rtc streaming with INMP441 + MAX98357A
# This configuration sends mic audio to go2rtc server and receives WebRTC audio
# The remote_ip/port are static - evaluated at boot time

substitutions:
  device_name: intercom-basic
  go2rtc_server: "192.168.1.10"

esphome:
  name: ${device_name}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG

api:
ota:
  - platform: esphome

# External components from local directory
external_components:
  - source:
      type: local
      path: ../custom_components
    components: [i2s_audio_udp]

# Core audio component - I2S mode auto-deduced from pins
i2s_audio_udp:
  id: audio_bridge
  # Dual bus pins (INMP441 + MAX98357A)
  mic_din_pin: 4
  mic_bclk_pin: 5
  mic_lrclk_pin: 6
  speaker_dout_pin: 15
  speaker_bclk_pin: 16
  speaker_lrclk_pin: 17
  # Mic configuration
  mic_bits_per_sample: 32
  mic_channel: left
  mic_gain: 4
  # Network - static IPs
  remote_ip: ${go2rtc_server}
  remote_port: 12345  # go2rtc input port
  listen_port: 12346  # go2rtc output port
  # Triggers
  on_start:
    - logger.log: "Audio streaming started"
  on_stop:
    - logger.log: "Audio streaming stopped"
  on_error:
    - logger.log:
        format: "Audio error: %s"
        args: [error.c_str()]

# Sensors for statistics
sensor:
  - platform: i2s_audio_udp
    i2s_audio_udp_id: audio_bridge
    tx_packets:
      name: "TX Packets"
    rx_packets:
      name: "RX Packets"

# Text sensor for audio mode
text_sensor:
  - platform: i2s_audio_udp
    i2s_audio_udp_id: audio_bridge
    audio_mode:
      name: "Audio Mode"

# Volume control
number:
  - platform: i2s_audio_udp
    i2s_audio_udp_id: audio_bridge
    volume:
      name: "Volume"

# Control switch
switch:
  - platform: template
    name: "Streaming"
    id: streaming_switch
    optimistic: true
    turn_on_action:
      - i2s_audio_udp.start:
          id: audio_bridge
    turn_off_action:
      - i2s_audio_udp.stop:
          id: audio_bridge
