# Example: P2P Intercom with mDNS discovery
# Devices discover each other via mDNS and stream audio directly
# All P2P logic (auto-answer, peer selection) handled in YAML

substitutions:
  device_name: intercom-p2p

esphome:
  name: ${device_name}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG

api:
ota:
  - platform: esphome

# Announce this device via mDNS
mdns:
  services:
    - service: "_udp-intercom"
      protocol: "_udp"
      port: 12346

# External components
external_components:
  - source:
      type: local
      path: ../custom_components
    components: [i2s_audio_udp, mdns_discovery]

# mDNS Discovery for peer finding
mdns_discovery:
  id: peer_discovery
  service_type: "udp-intercom"
  scan_interval: 10s
  peer_timeout: 60s
  on_peer_found:
    - logger.log:
        format: "Peer found: %s (%s:%d)"
        args: [name.c_str(), ip.c_str(), port]
    - text_sensor.template.publish:
        id: discovered_peers
        state: !lambda 'return id(peer_discovery).get_peers_list();'
  on_peer_lost:
    - logger.log:
        format: "Peer lost: %s"
        args: [name.c_str()]
    - text_sensor.template.publish:
        id: discovered_peers
        state: !lambda 'return id(peer_discovery).get_peers_list();'

# Core audio component
i2s_audio_udp:
  id: audio_bridge
  # Dual bus pins
  mic_din_pin: 4
  mic_bclk_pin: 5
  mic_lrclk_pin: 6
  speaker_dout_pin: 15
  speaker_bclk_pin: 16
  speaker_lrclk_pin: 17
  # Mic config
  mic_bits_per_sample: 32
  mic_channel: left
  mic_gain: 4
  # Network - TEMPLATABLE: evaluated at start() time
  remote_ip: !lambda 'return id(target_peer_ip).state;'
  remote_port: 12346
  listen_port: 12346
  on_start:
    - switch.template.publish:
        id: streaming_switch
        state: true
    - text_sensor.template.publish:
        id: status_text
        state: "STREAMING"
  on_stop:
    - switch.template.publish:
        id: streaming_switch
        state: false
    - text_sensor.template.publish:
        id: status_text
        state: "IDLE"

# Sensors
sensor:
  - platform: i2s_audio_udp
    i2s_audio_udp_id: audio_bridge
    tx_packets:
      name: "TX Packets"
    rx_packets:
      name: "RX Packets"
  - platform: mdns_discovery
    mdns_discovery_id: peer_discovery
    peer_count:
      name: "Peer Count"

# Text sensors
text_sensor:
  - platform: template
    name: "Status"
    id: status_text
    lambda: 'return std::string("IDLE");'
  - platform: template
    name: "Discovered Peers"
    id: discovered_peers
    lambda: 'return id(peer_discovery).get_peers_list();'
    update_interval: 10s

# Manual peer IP input
text:
  - platform: template
    name: "Target Peer IP"
    id: target_peer_ip
    optimistic: true
    mode: text
    initial_value: ""
    on_value:
      - logger.log:
          format: "Target IP set to: %s"
          args: [x.c_str()]

# Volume control
number:
  - platform: i2s_audio_udp
    i2s_audio_udp_id: audio_bridge
    volume:
      name: "Volume"

# Control switches
switch:
  - platform: template
    name: "Streaming"
    id: streaming_switch
    optimistic: true
    turn_on_action:
      - if:
          condition:
            lambda: 'return !id(target_peer_ip).state.empty();'
          then:
            - i2s_audio_udp.start:
                id: audio_bridge
          else:
            - logger.log: "Cannot start: no target IP set"
    turn_off_action:
      - i2s_audio_udp.stop:
          id: audio_bridge

  - platform: template
    name: "Auto Answer"
    id: auto_answer_switch
    optimistic: true

# Buttons
button:
  - platform: template
    name: "Call First Peer"
    on_press:
      - lambda: |-
          if (id(peer_discovery).get_peer_count() > 0) {
            std::string ip = id(peer_discovery).get_peer_ip(0);
            id(target_peer_ip).publish_state(ip);
            id(streaming_switch).turn_on();
          } else {
            ESP_LOGW("p2p", "No peers discovered");
          }

  - platform: template
    name: "Refresh Peers"
    on_press:
      - mdns_discovery.scan:
          id: peer_discovery

  - platform: restart
    name: "Restart"

# Auto-answer interval (P2P incoming packet detection)
interval:
  - interval: 100ms
    then:
      - if:
          condition:
            and:
              - switch.is_on: auto_answer_switch
              - lambda: 'return !id(audio_bridge).is_streaming();'
          then:
            # Check for incoming UDP packets on listen port
            # This would need native UDP component or custom lambda
            # For now, rely on manual calling
            - lambda: |-
                // Auto-answer logic would go here
                // In practice, use ESPHome's native udp component
                // to detect incoming packets and trigger start
                ;
