# Example: Single Bus with ES8311 codec (Xiaozhi Ball style)
# ES8311 uses a single I2S bus for both mic and speaker
# The codec is configured via I2C separately

substitutions:
  device_name: intercom-xiaozhi
  go2rtc_server: "192.168.1.10"

esphome:
  name: ${device_name}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  hardware_uart: USB_SERIAL_JTAG

api:
ota:
  - platform: esphome

# I2C for ES8311 codec configuration
i2c:
  sda: 41
  scl: 42
  scan: true

# ES8311 codec (configured separately - handles DAC/ADC)
# es8311:
#   address: 0x18

external_components:
  - source:
      type: local
      path: ../custom_components
    components: [i2s_audio_udp]

# Audio bridge - SINGLE bus (auto-deduced from i2s_* pins)
i2s_audio_udp:
  id: audio_bridge
  # Single bus pins (shared for mic and speaker via codec)
  i2s_lrclk_pin: 8
  i2s_bclk_pin: 18
  i2s_mclk_pin: 16
  i2s_din_pin: 17   # Mic data from codec
  i2s_dout_pin: 15  # Speaker data to codec
  sample_rate: 16000
  # Network
  remote_ip: ${go2rtc_server}
  remote_port: 12345
  listen_port: 12346
  on_start:
    - logger.log: "ES8311 streaming started"
  on_stop:
    - logger.log: "ES8311 streaming stopped"

# Sensors
sensor:
  - platform: i2s_audio_udp
    i2s_audio_udp_id: audio_bridge
    tx_packets:
      name: "TX Packets"
    rx_packets:
      name: "RX Packets"

text_sensor:
  - platform: i2s_audio_udp
    i2s_audio_udp_id: audio_bridge
    audio_mode:
      name: "Audio Mode"

# Volume (hardware via ES8311 I2C, or software fallback)
number:
  - platform: i2s_audio_udp
    i2s_audio_udp_id: audio_bridge
    volume:
      name: "Volume"

# Control
switch:
  - platform: template
    name: "Streaming"
    id: streaming_switch
    optimistic: true
    turn_on_action:
      - i2s_audio_udp.start:
          id: audio_bridge
    turn_off_action:
      - i2s_audio_udp.stop:
          id: audio_bridge

button:
  - platform: restart
    name: "Restart"
