# Example: Intercom with Acoustic Echo Cancellation (AEC)
# Uses ESP-SR AFE for echo cancellation during full-duplex audio

substitutions:
  device_name: intercom-aec
  go2rtc_server: "192.168.1.10"

esphome:
  name: ${device_name}
  platformio_options:
    # ESP-SR requires PSRAM and significant flash
    board_build.flash_size: 8MB
    board_build.partitions: default_8MB.csv

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_SPIRAM_MODE_OCT: y
      CONFIG_SPIRAM_SPEED_80M: y

psram:
  mode: octal
  speed: 80MHz

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG

api:
ota:
  - platform: esphome

external_components:
  - source:
      type: local
      path: ../custom_components
    components: [i2s_audio_udp, esp_aec]

# AEC component - initializes ESP-SR AFE
esp_aec:
  id: echo_canceller
  sample_rate: 16000
  filter_length: 4

# Audio bridge with AEC
i2s_audio_udp:
  id: audio_bridge
  # Dual bus pins
  mic_din_pin: 4
  mic_bclk_pin: 5
  mic_lrclk_pin: 6
  speaker_dout_pin: 15
  speaker_bclk_pin: 16
  speaker_lrclk_pin: 17
  # Mic config
  mic_bits_per_sample: 32
  mic_channel: left
  mic_gain: 4
  # Network
  remote_ip: ${go2rtc_server}
  remote_port: 12345
  listen_port: 12346
  # Link AEC
  aec_id: echo_canceller
  on_start:
    - logger.log: "Audio with AEC started"
  on_stop:
    - logger.log: "Audio with AEC stopped"

# Sensors
sensor:
  - platform: i2s_audio_udp
    i2s_audio_udp_id: audio_bridge
    tx_packets:
      name: "TX Packets"
    rx_packets:
      name: "RX Packets"

# Volume
number:
  - platform: i2s_audio_udp
    i2s_audio_udp_id: audio_bridge
    volume:
      name: "Volume"

# Control
switch:
  - platform: template
    name: "Streaming"
    id: streaming_switch
    optimistic: true
    turn_on_action:
      - i2s_audio_udp.start:
          id: audio_bridge
    turn_off_action:
      - i2s_audio_udp.stop:
          id: audio_bridge
